name: Deploy to Cloud Run

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  SERVICE_NAME: receiptapp
  REGION: australia-southeast2

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars "DEBUG=False,CUSTOM_DOMAIN=${{ secrets.CUSTOM_DOMAIN }}" \
            --set-secrets=SECRET_KEY=receiptapp-secret-key:latest,DATABASE_URL=receiptapp-db-url:latest,GS_BUCKET_NAME=receiptapp-gs-bucket-name:latest,OPENROUTER_API_KEY=receiptapp-openrouter-api-key:latest,OPENROUTER_MODEL=receiptapp-openrouter-model:latest \
            --add-cloudsql-instances ${{ secrets.GCP_SQL_INSTANCE_NAME }}

      - name: Run Django Management Commands
        uses: google-github-actions/run-command@v0
        with:
          command: |-
            python manage.py migrate
            python manage.py collectstatic --noinput
          image: ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          service_account: ${{ secrets.GCP_SA_KEY }}
          secrets: |-
            SECRET_KEY=receiptapp-secret-key:latest
            DATABASE_URL=receiptapp-db-url:latest
            GS_BUCKET_NAME=receiptapp-gs-bucket-name:latest
            OPENROUTER_API_KEY=receiptapp-openrouter-api-key:latest
            OPENROUTER_MODEL=receiptapp-openrouter-model:latest
          env: |-
            DEBUG=False
            CUSTOM_DOMAIN=${{ secrets.CUSTOM_DOMAIN }}